version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3100 -b '0.0.0.0'"
    volumes:
      - .:/ByteMe-Docker
    ports:
      - "3100:3100"
    depends_on:
      - db
volumes:
  postgres:




